name: Binaries

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.17.x'
      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-image-dev
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
      - name: build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build/release
          cmake --build build/release --config Release
          mkdir build/release/bin/resources
          cp -r resources/* build/release/bin/resources
          chmod +x build/release/bin/ode_app
          chmod +x build/release/bin/example_app
      - uses: actions/upload-artifact@v2
        with:
          name: linux-bin
          path: ./build/release/bin

  macos:
    runs-on: macos-latest
    name: Build on Mac OS

    steps:
      - uses: actions/checkout@v2.1.0
      - name: build
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build/release
          cmake --build build/release --config Release
          mkdir build/release/bin/resources
          cp -r resources/* build/release/bin/resources
          chmod +x build/release/bin/ode_app
          chmod +x build/release/bin/example_app
      - uses: actions/upload-artifact@v2
        with:
          name: mac-bin
          path: ./build/release/bin

  windows:
    runs-on: windows-latest
    name: Build on Windows

    steps:
      - uses: actions/checkout@v2.1.0
      - name: build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build/release
          cmake --build build/release --config Release
          mkdir build\release\bin\Release\resources
          xcopy /E /I resources build\release\bin\Release\resources
      - uses: actions/upload-artifact@v2
        with:
          name: windows-bin
          path: ./build/release/bin
